fix: add specific message and abort env loading if layer rabbitmq@mfe…
metwork-framework/mfbus pull request #32
Opened 2020-10-13 15:06 UTC by thebaptiste

…xt is not installed

2020-10-14 07:21 UTC, thefab commented on adm/profile.custom
> +if test ! -d ${MFEXT_HOME}/opt/rabbitmq; then
```suggestion
N=$(is_layer_installed rabbitmq@mfext)
if test "${N}" != "1"; then
```

2020-10-14 07:21 UTC, thefab requested changes

2020-10-14 07:21 UTC, thefab commented on adm/profile.custom
> +if test ! -d ${MFEXT_HOME}/opt/rabbitmq; then
not tested but probably better :)

2020-10-15 13:50 UTC, thebaptiste commented
I close this pull request. 
We fix this problem in mfext in this [PR](https://github.com/metwork-framework/mfext/pull/924)

2020-10-15 13:50 UTC, closed without merging